name: CI
on: [push]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v1
    - uses: php-actions/phpunit@v9
    - uses: symfonycorp/security-checker-action@v4

